"""separate driver application and availability status

Revision ID: 35beb4068a11
Revises: 43449c1f9a10
Create Date: 2026-09-17 23:40:22.088093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35beb4068a11'
down_revision: Union[str, Sequence[str], None] = '43449c1f9a10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. Add new columns temporarily allowing NULL
    op.add_column(
        'drivers',
        sa.Column(
            'application_status',
            sa.String(length=20),
            nullable=True
        )
    )

    op.add_column(
        'drivers',
        sa.Column(
            'availability_status',
            sa.String(length=20),
            nullable=True
        )
    )

    # 2. Copy old status into application_status
    op.execute(
        """
        UPDATE drivers
        SET application_status = status
        """
    )

    # 3. Set default availability for existing drivers
    op.execute(
        """
        UPDATE drivers
        SET availability_status = 'offline'
        """
    )

    # 4. Make both columns NOT NULL
    op.alter_column(
        'drivers',
        'application_status',
        existing_type=sa.String(length=20),
        nullable=False
    )

    op.alter_column(
        'drivers',
        'availability_status',
        existing_type=sa.String(length=20),
        nullable=False
    )

    # 5. Remove old status column
    op.drop_column(
        'drivers',
        'status'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drivers', sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.drop_column('drivers', 'availability_status')
    op.drop_column('drivers', 'application_status')
    # ### end Alembic commands ###
